title: Patricio Reyes Gallardo
description: business innovation
site_title: 'Patricio Reyes

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: patricioreyesgallardo
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com
keybase_username: abhn
instragam_username: 
tiktok_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
