title: Patricio Reyes Gallardo
description: business innovation
site_title: 'Patricio Reyes

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: patricioreyesgallardo
blog_url: https://www.nagekar.com
email: reyesgallardopatricio@gmail.com
keybase_username: patricio
instragam_username: _pato_reyes
tiktok_username: _pato_reyes_

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
